### ISSUE TITLE
Creating collection fails with ChromaDB >v0.6.2

### ISSUE THREAD

**Issue by mempirate** [amikos-tech/chroma-go#192]
## Context
I'm testing out Chroma-go with a Chroma DB 0.6.3 server running in docker. Compose setup is shown below.

When creating a collection like so:
```go
newCollection, err = client.NewCollection(
	context.TODO(),
	"test-collection",
	collection.WithMetadata("key1", "value1"),
	// NOTE: Apparently OpenAI embeddings are optimized for cosine distance
	collection.WithHNSWDistanceFunction(types.COSINE),
	collection.WithEmbeddingFunction(embedding),
)

if err != nil {
	log.Fatalf("Error creating collection: %s \n", err)
}
```
The following error is printed:
```
Error creating collection: Error (400) InvalidArgumentError: cannot unpack non-iterable coroutine object 
```
From the container logs, it seems that `GET /api/v1/tenants/default_tenant` call fails:
```
server-1  | INFO:     192.168.97.1:42134 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 400 Bad Request
```
Is this expected, maybe because of API deprecation? It doesn't happen in v0.6.2.

## Docker Compose
```yml
networks:
  net:
    driver: bridge
services:
  server:
    image: ghcr.io/chroma-core/chroma:0.6.3
    environment:
      # Set to true to persist data to disk
      - IS_PERSISTENT=FALSE
    # volumes:
      # Default configuration for persist_directory in chromadb/config.py
      # Currently it's located in "/chroma/chroma/"
      # - chroma-data:/chroma/chroma/
    ports:
      - 8000:8000
    networks:
      - net
    healthcheck:
      # Adjust below to match your container port
      test: [ "CMD", "curl", "-f", "http://localhost:8000/api/v2/heartbeat" ]
      interval: 30s
      timeout: 10s
      retries: 3
    command: "--workers 1 --host 0.0.0.0 --port 8000 --proxy-headers --timeout-keep-alive 30"


volumes:
  chroma-data:
    driver: local
```
